### ISSUE TITLE
Developing the wish list feature

### ISSUE THREAD

**Issue by melaasar** [cs130-w22/template#1]
## User Story
As a **[Role]**, I would like **[Requirement]** so that **[Reason]**.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

## Tasks
- [ ] Create database
- [ ] Develop web service for x
- [ ] ss
